### PR TITLE
Fixes #1167

### LINKED ISSUE #1167: Incorrect login token causes an unhandled promise rejection

### PR DESCRIPTION
**Pull request by cjmyers**

### CODE REVIEW

**Comment by cjmyers** [comment]
Fixed problems with logout via the API.  It was not actually logging out via the API, and it also was not checking correctly if one is logged out before sending along.

File: lib/apiTokens.js [hunk 1]
```diff
@@ -11,6 +11,9 @@ function createToken (user) {
 
   return token
 }
+function deleteToken (token) {
+  tokens[token] = null
```
Comment (3ach) [inline lib/apiTokens.js]: should be `delete tokens[token]`
