### PR TITLE
Fixes promise rejection when SendGrid returns an error

### LINKED ISSUE #1214: Unhandled promise rejection error when bad request to SendGrid
When doing something that causes a request to SendGrid, such as adding a new user, there is an unhandled promise rejection when the SendGrid configuration is invalid.

error: (node:40386) UnhandledPromiseRejectionWarning: SendGridError: Response error
    at /Users/myers/git/synbiohub/node_modules/sendgrid/lib/sendgrid.js:123:19
    at IncomingMessage.<anonymous> (/Users/myers/git/synbiohub/node_modules/sendgrid-rest/lib/client.js:112:9)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
error: (node:40386) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

### PR DESCRIPTION
**Pull request by cjmyers**
Closes #1214 
This happens, for example, when there is no valid API key specified

### CODE REVIEW

**Comment by cjmyers** [comment]
Closes #1214

File: lib/views/resetPassword.js [hunk 1]
```diff
@@ -56,17 +56,47 @@ function resetPasswordPost (req, res) {
...
+    if (err === {}) {
+      if (!req.accepts('text/html')) {
+        return res.status(200).header('content-type', 'text/plain').send('If a user was found associated with the specified e-mail address, a link to reset your password has been sent.')
+      } else {
+        res.send(pug.renderFile('templates/views/resetPasswordDone.jade', locals))
+      }
     } else {
-      res.send(pug.renderFile('templates/views/resetPasswordDone.jade', locals))
+      var error = err
+      var statusCode = 500
```
Comment (3ach) [inline lib/views/resetPassword.js:75]: I think you can just do `statusCode = err.response.statusCode || 500`

File: lib/views/resetPassword.js [hunk 2]
```diff
@@ -56,17 +56,47 @@ function resetPasswordPost (req, res) {
...
+      if (err.message) {
```
Comment (3ach) [inline lib/views/resetPassword.js:76]: Do you only have `err.response` when you have `err.message`?

File: lib/views/resetPassword.js (hunk 1 above)
Comment (cjmyers) [reply lib/views/resetPassword.js:75]: What if err is undefined?  Would this not create an exception?  The logic is complex because I was not entirely sure what I would be getting back.  This is a error returned by Sendgrid.  I was being very particular, since I was parsing the JSON coming back, and I think assuming and dereferencing can lead to exceptions.  I'm not sure though about the syntax you give though if that is more robust to dereference problems.

File: lib/views/resetPassword.js (hunk 2 above)
Comment (cjmyers) [reply lib/views/resetPassword.js:76]: I'm not sure.  I just looked at what Sendgrid sent back, and I parsed it out.  However, I was nervous that I could not rely on the JSON structure to be fixed.

File: lib/views/resetPassword.js (hunk 1 above)
Comment (3ach) [reply lib/views/resetPassword.js:75]: I just tested, and it will create an exception. Can be left as-is.
