### PR TITLE
Fix bug with attachUrl when no type is selected

### LINKED ISSUE #1180: Attachurl broken
AttachURL crashes SynBioHub

### PR DESCRIPTION
**Pull request by cjmyers**
Closes #1180

### CODE REVIEW

File: lib/api/attachUrl.js [hunk 1]
```diff
@@ -25,6 +25,14 @@ async function serve (req, res) {
     // error
   }
 
+  if (typeString === 'Pick an attachment type...') {
+    if (!req.accepts('text/html')) {
+      res.status(400).send('Must pick an attachment type')
+    } else {
+      res.redirect(url)
```
Comment (3ach) [inline lib/api/attachUrl.js:32]: Shouldn't it display an error on the page?

Comment (cjmyers) [reply lib/api/attachUrl.js:32]: Agreed, but I was not sure how to do that.  Ideally, there should be popups with this one and the add/edit/remove fields ones when something goes wrong.  I settled on simply refreshing the page.
